// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RedeSocial.Postagem.Infrastructure.Context;

#nullable disable

namespace RedeSocial.Postagem.Infrastructure.Migrations
{
    [DbContext(typeof(PostagemContext))]
    partial class PostagemContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.5");

            modelBuilder.Entity("RedeSocial.Postagem.Domain.PostagemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataPostagem")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PostagemPublica")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PostagemEntities");
                });
#pragma warning restore 612, 618
        }
    }
}
